package MP14SMMA.SERVER.MODEL;
// Generated 21-may-2019 12:14:37 by Hibernate Tools 5.3.6.Final

/**
 * Attend generated by hbm2java
 */
public class Attend implements java.io.Serializable {

	private AttendId id;

	public Attend() {
	}

	public Attend(AttendId id) {
		this.id = id;
	}

	public AttendId getId() {
		return this.id;
	}

	public void setId(AttendId id) {
		this.id = id;
	}

}
