package MP14SMMA.SERVER.MODEL;
// Generated 21-may-2019 12:14:37 by Hibernate Tools 5.3.6.Final

/**
 * DinnerTable generated by hbm2java
 */
public class DinnerTable implements java.io.Serializable {

	private int idTable;
	private String locationTable;
	private Integer numberDinersTable;

	public DinnerTable() {
	}

	public DinnerTable(int idTable) {
		this.idTable = idTable;
	}

	public DinnerTable(int idTable, String locationTable, Integer numberDinersTable) {
		this.idTable = idTable;
		this.locationTable = locationTable;
		this.numberDinersTable = numberDinersTable;
	}

	public int getIdTable() {
		return this.idTable;
	}

	public void setIdTable(int idTable) {
		this.idTable = idTable;
	}

	public String getLocationTable() {
		return this.locationTable;
	}

	public void setLocationTable(String locationTable) {
		this.locationTable = locationTable;
	}

	public Integer getNumberDinersTable() {
		return this.numberDinersTable;
	}

	public void setNumberDinersTable(Integer numberDinersTable) {
		this.numberDinersTable = numberDinersTable;
	}

}
