package MP14SMMA.SERVER.MODEL;
// Generated 21-may-2019 11:53:53 by Hibernate Tools 5.3.6.Final

/**
 * Dish generated by hbm2java
 */
public class Dish implements java.io.Serializable {

	private Integer idItemDish;
	private float price;
	private String nameDish;
	private int quantityStock;
	private int statusDish;
	private String descriptionDish;
	private String dniKitchen;

	public Dish() {
	}

	public Dish(float price, String nameDish, int quantityStock, int statusDish) {
		this.price = price;
		this.nameDish = nameDish;
		this.quantityStock = quantityStock;
		this.statusDish = statusDish;
	}

	public Dish(float price, String nameDish, int quantityStock, int statusDish, String descriptionDish,
			String dniKitchen) {
		this.price = price;
		this.nameDish = nameDish;
		this.quantityStock = quantityStock;
		this.statusDish = statusDish;
		this.descriptionDish = descriptionDish;
		this.dniKitchen = dniKitchen;
	}

	public Integer getIdItemDish() {
		return this.idItemDish;
	}

	public void setIdItemDish(Integer idItemDish) {
		this.idItemDish = idItemDish;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public String getNameDish() {
		return this.nameDish;
	}

	public void setNameDish(String nameDish) {
		this.nameDish = nameDish;
	}

	public int getQuantityStock() {
		return this.quantityStock;
	}

	public void setQuantityStock(int quantityStock) {
		this.quantityStock = quantityStock;
	}

	public int getStatusDish() {
		return this.statusDish;
	}

	public void setStatusDish(int statusDish) {
		this.statusDish = statusDish;
	}

	public String getDescriptionDish() {
		return this.descriptionDish;
	}

	public void setDescriptionDish(String descriptionDish) {
		this.descriptionDish = descriptionDish;
	}

	public String getDniKitchen() {
		return this.dniKitchen;
	}

	public void setDniKitchen(String dniKitchen) {
		this.dniKitchen = dniKitchen;
	}

}
