package MP14SMMA.SERVER.MODEL;
// Generated 21-may-2019 12:14:37 by Hibernate Tools 5.3.6.Final

/**
 * HasdishId generated by hbm2java
 */
public class HasdishId implements java.io.Serializable {

	private int idTicket;
	private int idItemDish;

	public HasdishId() {
	}

	public HasdishId(int idTicket, int idItemDish) {
		this.idTicket = idTicket;
		this.idItemDish = idItemDish;
	}

	public int getIdTicket() {
		return this.idTicket;
	}

	public void setIdTicket(int idTicket) {
		this.idTicket = idTicket;
	}

	public int getIdItemDish() {
		return this.idItemDish;
	}

	public void setIdItemDish(int idItemDish) {
		this.idItemDish = idItemDish;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HasdishId))
			return false;
		HasdishId castOther = (HasdishId) other;

		return (this.getIdTicket() == castOther.getIdTicket()) && (this.getIdItemDish() == castOther.getIdItemDish());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdTicket();
		result = 37 * result + this.getIdItemDish();
		return result;
	}

}
