package MP14SMMA.SERVER.MODEL;
// Generated 21-may-2019 12:14:37 by Hibernate Tools 5.3.6.Final

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String dni;
	private String firstName;
	private String surnames;
	private String phoneNumber;
	private String accessKey;
	private int kind;

	public Users() {
	}

	public Users(String dni, String firstName, String surnames, String accessKey, int kind) {
		this.dni = dni;
		this.firstName = firstName;
		this.surnames = surnames;
		this.accessKey = accessKey;
		this.kind = kind;
	}

	public Users(String dni, String firstName, String surnames, String phoneNumber, String accessKey, int kind) {
		this.dni = dni;
		this.firstName = firstName;
		this.surnames = surnames;
		this.phoneNumber = phoneNumber;
		this.accessKey = accessKey;
		this.kind = kind;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getSurnames() {
		return this.surnames;
	}

	public void setSurnames(String surnames) {
		this.surnames = surnames;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public String getAccessKey() {
		return this.accessKey;
	}

	public void setAccessKey(String accessKey) {
		this.accessKey = accessKey;
	}

	public int getKind() {
		return this.kind;
	}

	public void setKind(int kind) {
		this.kind = kind;
	}

}
